apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: yolo-app
  labels:
    app: mongodb
type: Opaque
stringData:
  password: "yolo-secure-mongo-pass-2026"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: yolo-app
  labels:
    app: backend
data:
  PORT: "5000"
  MONGODB_URI: "mongodb://admin:yolo-secure-mongo-pass-2026@mongodb:27017/yolomy?authSource=admin"
  NODE_ENV: "production"
